version: "3.4"

services:
  db:
    image: postgres:10.6-alpine
    environment:
      POSTGRES_DB: app
    networks:
      - ride
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:


networks:
  ride:
    external: true
